#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/arares/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

#xset s off &
#xset s noblank &
#xset +dpms &
# the above is needed for unwanted screen blanking
# /home/arares/monitor.sh &
klipper &
kmix &
nm-applet &
fbsetbg -a pics/wlp/GThibault_KonaProcess_NSMB_KazYamamura-26.jpg &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/arares/.fluxbox/log"
